name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
      - run: cd app
      - run: make lint
      - run: make test
      - name: Publish code coverage
        uses: qltysh/qlty-action/coverage@main
        with:
          coverageCommand: make report
            coverage-token:{{secrets.QLTY_COVERAGE_TOKEN}}
            files:target/lcov.info
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
        env:
          QLTY_COVERAGE_TOKEN: ${{secrets.QLTY_COVERAGE_TOKEN}}
          JACOCO_SOURCE_PATH: ${{github.workspace}}/app/src/main/java
          
