name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: build
          build-root-directory: app
      #- run: ./gradlew checkstyleMain
      #- run: ./gradlew test
      - name: Publish code coverage
        uses: qltysh/qlty-action/coverage@main
        env:
          CC_TEST_REPORTER_ID: ${{secrets.QLTY_COVERAGE_TOKEN}}
          JACOCO_SOURCE_PATH: app/src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
          coverage-token: {{secrets.QLTY_COVERAGE_TOKEN}}
	  files: reports/coverage.xml
